---
driver:
  name: vagrant
  network:
  - ["private_network", {ip: "33.33.33.72"}]
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero
  # always_update_cookbooks: true

platforms:
  - name: ubuntu-14.04
  # - name: ubuntu-16.04
  # - name: centos-6.8
  # - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[wordpress::setup]
    attributes:
      wordpress:
        site:
          url: http://33.33.33.72
