---
driver:
  name: vagrant
  network:
  - ['forwarded_port', {guest: 80, host: 8080, auto_correct: true}]
  - ['forwarded_port', {guest: 443, host: 8443, auto_correct: true}]
  customize:
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[wordpress::default]
    attributes:
